/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  theorySidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['Theory/Introduction/definition',
        'Theory/Introduction/history',
        'Theory/Introduction/components',
        'Theory/Introduction/architecture',
        'Theory/Introduction/applications',
        'Theory/Introduction/challenges',
      ],
    },
    {
      type: 'category',
      label: 'Perception Layer',
      items: ['Theory/PerceptionLayer/section1',
      ],
    },
  ],

  labsSidebar: [
    'Labs/lab1',
    'Labs/lab2',

  ],
};

export default sidebars;
